#!/bin/bash
#adds all the python scripts to bash
git add git_add_script #script that adds itself to git
git add geno_distbs/varying_susceps/geno_distb_analyser.ipynb #big run analyser for varying susceptibilities
git add parameter_diagnostics/optimal_r_det-N.ipynb #used for finding optimal N* and detatchment rate - OLD
git add parameter_diagnostics/ms_diags_results #data used for the optiman N* and detachment rate
git add parameter_diagnostics/optimal_param_pairs.ipynb #used for finding optimal N* and detachment rate
git add timeToFailure_varyingSuscep/ttf_analyser.ipynb #the time to failure for the varying susceptibilities
git add biofilm_threshold_theory/bf_thresh_theory_plotter.ipynb #various plots from stocastic version of biofilm threshold theory

git commit -m "$1"
