#!/bin/bash
#adds all the python scripts to git (hopefully PAT works)
git add git_add_script #script that adds itself to git

git add geno_distbs/varying_susceps/geno_distb_analyser.ipynb #big run analyser for varying susceptibilities
git add geno_distbs/varying_susceps/multispecies_shannon_calculator.ipynb #calculates the shannon variables for the multispecies runs
git add geno_distbs/varying_susceps/multispecies_shannon_calculator_v2.ipynb # shannon calculator for the low migration rate runs
git add geno_distbs/varying_susceps/multispecies_shannon_plotter.ipynb #plots the shannon variables for the multispecies runs
git add geno_distbs/varying_susceps/multispecies_shannon_plotter_v2.ipynb # shannon plotter for the low migration rate runs
git add geno_distbs/varying_susceps/geno_distb_plotter.ipynb #plots the genotype distributions (the big pink and blue plots)
git add geno_distbs/varying_susceps/ttf_analyser.ipynb #time to failure analyser

git add parameter_diagnostics/optimal_r_det-N.ipynb #used for finding optimal N* and detatchment rate - OLD
git add parameter_diagnostics/ms_diags_results #data used for the optimal N* and detachment rate
git add parameter_diagnostics/optimal_param_pairs.ipynb #used for finding optimal N* and detachment rate


git add biofilm_threshold_theory/bf_thresh_theory_plotter.ipynb #various plots from stocastic version of biofilm threshold theory
git add biofilm_threshold_theory/stochastic_lagTime_analyser.ipynb #plots for the stochastic lag time (noise to reach microhabitat n)
git add biofilm_threshold_theory/phase_diagram_plotter.ipynb #plots the phase diagram for the time taken to reach the first microhabitat
git add biofilm_threshold_theory/phase_diagram_plotter_v2.ipynb #plots the phase diagram for the time taken to reach the first microhabitat
git add biofilm_threshold_theory/species_comp_analyser.ipynb #analyses the difference in species composition between the phase2 and phase4 regimes
git add biofilm_threshold_theory/species_comp_analyser_v2.ipynb #analyses the difference in species composition between the phase2 and phase4 regimes (improved version)
git add biofilm_threshold_theory/species_comp_analyser_v3.ipynb #analyses the species composition, does shannon calculations but without the memory issues
git add biofilm_threshold_theory/species_comp_plotter.ipynb #makes plots of the shannon caluclations for the two phases
git add biofilm_threshold_theory/allen_presentation_plots.ipynb #plots of the effect of N* on population growth

git add biofilm_threshold_theory/paper_plots/modeldiagram.svg #inkscape file of the bftt model diagram

git add lognorm_diagnostics/lognorm_analyser.ipynb #calculates mu and sigma for the log norm MIC distributions

git add Testing_phase/PyrithionePlotter.ipynb # the old plotting scripts for lognorms/MIC half lifes.

git commit -m "$1"

git push -u origin master
